
### Signup
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"password"
}

### Login
POST http://localhost:4000/auth/login
Content-Type: application/json

 {
    "email":"test@test.com",
    "password":"password"
}

### Logout
POST http://localhost:4000/auth/logout
Content-Type: application/json

### Get all Users
GET http://localhost:4000/users

### Get CurrentUser
GET http://localhost:4000/users/me

### Get One User
GET http://localhost:4000/users/3

### Update user
PATCH http://localhost:4000/users/3
Content-Type: application/json

{
 "email":"oyewoledamilare@email.com"
}

### Get One User
DELETE http://localhost:4000/users/3